################################### USER ROUTES ###################################


#  USER REGISTRATION
POST http://localhost:5000/user/register
Content-Type: application/json

{
    "userId": 24,
    "name": "pranav",
    "email": "pranav@westagilelab.com",
    "password": "pranav"
}

###

#  USER LOGIN
POST http://localhost:5000/user/login
Content-Type: application/json

{

     
    "email": "mohit@westagilelab.com",
    "password": "mohit"
}

###


# USER FORGOT PASSWORD

POST http://localhost:5000/user/forgot-password
Content-Type: application/json

{
    "email": "mohit@westagilelab.com"
}

###

# USER PASSWORD RESET

PUT http://localhost:5000/user/reset-password/mohit@westagilelab.com/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1vaGl0QHdlc3RhZ2lsZWxhYi5jb20iLCJpYXQiOjE2ODA3Njc0NjYsImV4cCI6MTY4MDc2ODM2Nn0.JlrXEb-_KhKdZvbZNI9AOzSAwJpEzalqmZD_Kt14KB4
Content-Type: application/json

{
    "password": "mohit"
}


### 

GET http://localhost:5000/user/reset-password/mohit@westagilelab.com/token












################################### SUPER ADMIN ROUTES ###################################

# LOGIN

POST http://localhost:5000/user/login
Content-Type: application/json

{
    "email": "super@westagilelab.com",
    "password": "super"
}


###

# ASSIGN ROLE TO EMPLOYEE

PUT http://localhost:5000/super-admin/assign-role
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsInVzZXJSb2xlIjoic3VwZXJBZG1pbiIsImlhdCI6MTY4MDI0MjIzNiwiZXhwIjoxNjgwMzI4NjM2fQ.Pwbub5dLYQjNaJx46nK4UFQYaonPp5qsZXgHn9ImZio
Content-Type: application/json

{
    "userId": 16,
    "role": "superAdmin" 
}

###

# GET ALL USERS

GET http://localhost:5000/super-admin/all-users
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsInVzZXJSb2xlIjoic3VwZXJBZG1pbiIsImlhdCI6MTY4MDI0MTc4MCwiZXhwIjoxNjgwMzI4MTgwfQ.PdbVxWf6uXkBkmmL1MKGtMpd72KIR5-UixjXoyARGzw

###

# ALL UNASSIGNED USERS

GET http://localhost:5000/super-admin/unassigned-users
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInVzZXJSb2xlIjoic3VwZXJBZG1pbiIsImlhdCI6MTY3ODg4MjEwNywiZXhwIjoxNjc4OTY4NTA3fQ.7sP_PQ8Z64dapt2dyzllDxsJuj06icjQsdmLflcnT-4

###










################################### GDO ROUTES #############################################


# LOGIN

POST http://localhost:5000/user/login
Content-Type: application/json

{
    "email": "gdo@westagilelab.com",
    "password": "gdo"
}

###


# ALL PROEJCTS UNDER GDO 
GET http://localhost:5000/gdo/5/all-projects
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsInVzZXJSb2xlIjoiZ2RvIiwiaWF0IjoxNjgwNjcxNTc0LCJleHAiOjE2ODA3NTc5NzR9.lkhWe-4rwDxo_IKg408abVJYcSKpJyo4_QPZiX4YaO8

###

# DETAILED VIEW OF PROJECT BY PROJECT ID

GET http://localhost:5000/gdo/gdoId/5/detailed-project-view/project/1
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsInVzZXJSb2xlIjoiZ2RvIiwiaWF0IjoxNjgwNjcxNTc0LCJleHAiOjE2ODA3NTc5NzR9.lkhWe-4rwDxo_IKg408abVJYcSKpJyo4_QPZiX4YaO8


###


# GDO CREATING RESOURCE REQUEST

POST http://localhost:5000/gdo/resource-request
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEwMCwidXNlclJvbGUiOiJnZG8iLCJpYXQiOjE2Nzg4ODMwNDUsImV4cCI6MTY3ODk2OTQ0NX0.K3pQ6FikdQZ9na46j0t6WS1CKjHbnEdTkYNUvpDlCkE
Content-Type: application/json

{
     
    "gdoId": 100,
    "projectId": 11,
    "requestdescription": "Need more 5 employees for this project!"
}

###

# CREATE A PROJECT
POST http://localhost:5000/gdo/create-project
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEwLCJ1c2VyUm9sZSI6ImdkbyIsImlhdCI6MTY3ODg0MzYxMCwiZXhwIjoxNjc4OTMwMDEwfQ.riCjxJWLWGVSrCPMH-MJAuiSU48kznHRFF0WwoTxFWs
Content-Type: application/json

{
    "projectId": 5,
    "projectName": "xyz project",
    "clientName": "west agile labs",
    "clientAccountManager": "sarthak",
    "projectStatus": "running",
    "projectStartDate": "2023-03-14",
    "projectEndDate": "2023-04-22",
    "projectFitnessIndicator": "G",
    "projectDomain": "devops",
    "projectType": "backend",
    "gdoId": 3,
    "projectManager": 1
}


###

# UPDATE PROJECT

PUT http://localhost:5000/gdo/update-project/project/1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsInVzZXJSb2xlIjoiZ2RvIiwiaWF0IjoxNjgwNjAzNTMxLCJleHAiOjE2ODA2ODk5MzF9.9jXKH5WS6c6Yd3j0cPgNu1QO-Kx_XNvFghk_7YPgjk0
Content-Type: application/json

{
    "projectId": 1,
    "projectName": "pulse2 project",
    "clientName": "west agile labs",
    "clientAccountManager": "shreya",
    "projectStatus": "running",
    "projectStartDate": "2023-03-14",
    "projectEndDate": "2023-04-14",
    "projectFitnessIndicator": "G",
    "projectDomain": "backend",
    "projectType": "backend",
    "gdoId": 5,
    "projectManager": 4
}

###



# ASSIGN A PROJECT TO EMPLOYEE

POST http://localhost:5000/gdo/assign-project
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsInVzZXJSb2xlIjoiZ2RvIiwiaWF0IjoxNjgwMDczOTk3LCJleHAiOjE2ODAxNjAzOTd9.2sFR7Ll8sIW2eGa6s5bPbIXNajJUhMXvprFLd9yWtLY
Content-Type: application/json

{
      "id": 18,
      "projectId": 1,
      "resourceName": "anjali",
      "role": "developer",
      "startDate": "2023-03-13",
      "endDate": "2023-03-15",
      "status": true,
      "billingStatus": "billed",
      "exposedToCustomer": true,
      "allocationType": "permanent"
}

###




# DELETE EMPLOYEE FROM PROJECT TEAM
DELETE http://localhost:5000/gdo/delete-member/1
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsInVzZXJSb2xlIjpudWxsLCJpYXQiOjE2Nzg3MjYyNTQsImV4cCI6MTY3ODgxMjY1NH0.58SM91XcE0SvLj1RuLwbyB2MYM9dsMm2wCsmoGJe5r0

###




# RAISE A PROJECT UPDATE

PUT http://localhost:5000/gdo/raise-project-update/project/1
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsInVzZXJSb2xlIjoicHJvamVjdE1hbmFnZXIiLCJpYXQiOjE2Nzg4ODM1OTksImV4cCI6MTY3ODk2OTk5OX0.z1aOkk9tFGWfZ1whowd0kV0LoPVCtkZ65sG7SkZwK1U
Content-Type: application/json

{
    "projectId": 1,
    "projectName": "pulse2222 project",
    "clientName": "west agile labs",
    "clientAccountManager": "shreya",
    "projectStatus": "running",
    "projectStartDate": "2023-03-14",
    "projectEndDate": "2023-04-14",
    "projectFitnessIndicator": "G",
    "projectDomain": "backend",
    "projectType": "backend",
    "gdoId": 3,
    "projectManager": 1
}

###




# DELETE PROJECT CONCERN

DELETE http://localhost:5000/gdo/delete-project-concern/4
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsInVzZXJSb2xlIjoiZ2RvIiwiaWF0IjoxNjgwNjcxNTc0LCJleHAiOjE2ODA3NTc5NzR9.lkhWe-4rwDxo_IKg408abVJYcSKpJyo4_QPZiX4YaO8


###













################################### SPECIAL USERS ROUTES ###################################


# LOGIN
POST http://localhost:5000/user/login
Content-Type: application/json

{
    "email": "specialUser@westagilelab.com",
    "password": "specialUser"
}

###




# ALL PROJECTS

GET http://localhost:5000/special-user/all-projects
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjYsInVzZXJSb2xlIjoic3BlY2lhbFVzZXIiLCJpYXQiOjE2ODAwMDMyNTEsImV4cCI6MTY4MDA4OTY1MX0.UnR6YYTHDpEPKSALtmRa-34gv4CB2dvGF2fmT7Y9g-U


###
 

 
# DETAILED PROJECT VIEW BY PROJECT ID
GET http://localhost:5000/special-user/detailed-view/project/5
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjYsInVzZXJSb2xlIjoic3BlY2lhbFVzZXIiLCJpYXQiOjE2ODA1MTg4MzEsImV4cCI6MTY4MDYwNTIzMX0.4IhskNCUAbtIaexmQcNZcXj_Ot62VNqTzsUB42nNV0k


###



# SPECIAL USER CREATE PROJECT

POST http://localhost:5000/special-user/create-project
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjYsInVzZXJSb2xlIjoic3BlY2lhbFVzZXIiLCJpYXQiOjE2ODAwMDM3NTksImV4cCI6MTY4MDA5MDE1OX0.zvfPziBnDKM3QBR1-msoEIsv3arNp92Dqpot5oIOvw8
Content-Type: application/json

{
    "projectId": 1,
    "projectName": "aws project",
    "clientName": "west agile labs",
    "clientAccountManager": "sarthak",
    "projectStatus": "running",
    "projectStartDate": "2023-03-14",
    "projectEndDate": "2023-04-22",
    "projectFitnessIndicator": "G",
    "projectDomain": "devops",
    "projectType": "backend",
    "gdoId": 5,
    "projectManager": 4
}
 
###



# ALL RESOURCE REQUESTS

###
GET http://localhost:5000/special-user/all-resource-requests
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjYsInVzZXJSb2xlIjoic3BlY2lhbFVzZXIiLCJpYXQiOjE2ODA2Nzc0OTksImV4cCI6MTY4MDc2Mzg5OX0.53wGEm_I9ICSL1P5NL-v-N6WF8CWjsK3uoliLMPjAHw

###




POST http://localhost:5000/user/login
Content-Type: application/json

{
    "email": "varun@westagilelab.com",
    "password": "varun"
}

###



# UPDATE A PROJECT
PUT http://localhost:5000/special-user/update-project/project/1
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsInVzZXJSb2xlIjoic3BlY2lhbFVzZXIiLCJpYXQiOjE2Nzg3NzM2ODAsImV4cCI6MTY3ODg2MDA4MH0.K6HQCD9P0x-OS_bJFNrtDT5ra6hm4gDTJC49zQ18Zkw
Content-Type: application/json

{
    "projectId": 1,
    "projectName": "pulse2 project",
    "clientName": "west agile labs",
    "clientAccountManager": "shreya",
    "projectStatus": "running",
    "projectStartDate": "2023-03-14",
    "projectEndDate": "2023-04-14",
    "projectFitnessIndicator": "G",
    "projectDomain": "backend",
    "projectType": "backend",
    "gdoId": 3,
    "projectManager": 1
}


###



# DELETE A PROJECT BY PROJECT ID

DELETE http://localhost:5000/special-user/delete-project/project/11
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsInVzZXJSb2xlIjoic3BlY2lhbFVzZXIiLCJpYXQiOjE2Nzg4ODIzMTQsImV4cCI6MTY3ODk2ODcxNH0.TQHEjSVssQ_O_WxH28JxHdJIB1Mws62wcdR0503cBu0


###


# DELETE RESOURCE REQUEST
DELETE http://localhost:5000/special-user/delete-resource-request/5
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjYsInVzZXJSb2xlIjoic3BlY2lhbFVzZXIiLCJpYXQiOjE2ODA2Nzc0OTksImV4cCI6MTY4MDc2Mzg5OX0.53wGEm_I9ICSL1P5NL-v-N6WF8CWjsK3uoliLMPjAHw
















################################### PROJECT MANAGER ROUTES ###################################

# ALL PROJECTS UNDER PROJECT MANAGER


POST http://localhost:5000/user/login
Content-Type: application/json

{
    "email": "projectManager@westagilelab.com",
    "password": "projectManager"
}

###



# GET PROJECTTS UNDER PROJECT MANAGER

GET http://localhost:5000/project-manager/projects-under-project-manager/7
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjcsInVzZXJSb2xlIjoicHJvamVjdE1hbmFnZXIiLCJpYXQiOjE2ODA1MTY1OTEsImV4cCI6MTY4MDYwMjk5MX0.DOlTP66ys0lqkAA7KbDaADd0KqCRqmNZIhc7hbi-VxE


###



# GET DETAILED VIEW OF A PROJECT

GET  http://localhost:5000/project-manager/detailed-project-view/project/1
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsInVzZXJSb2xlIjoicHJvamVjdE1hbmFnZXIiLCJpYXQiOjE2ODA0MTQ4NjgsImV4cCI6MTY4MDUwMTI2OH0.OzHz3FMcHDF4Zt3EIR4wN26Z0aNaTX0k-OnSA7_vYHI

###




# RAISE PROJECT CONCERN

POST http://localhost:5000/project-manager/raise-project-concern/project/10
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsInVzZXJSb2xlIjoicHJvamVjdE1hbmFnZXIiLCJpYXQiOjE2ODA2OTc0MjgsImV4cCI6MTY4MDc4MzgyOH0.u1ZN5bHzrFC9HSUerqMB3LvofFAtsE8110S2VcmE63o
Content-Type: application/json

{
	"projectId": 10,
	"concernDescription": "Need 5 devs",
	"raisedBy": "Shamir",
	"raisedOn": "2023-02-23",
	"severityOfConcern": "moderate",
	"raisedInternally": true,
	"status": "active",
	"concernMitigationDate": "2023-02-28",
	"projectManager": 7

}

###



# RAISE PROJECT UPDATE

POST http://localhost:5000/project-manager/raise-project-update/project/1
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsInVzZXJSb2xlIjoicHJvamVjdE1hbmFnZXIiLCJpYXQiOjE2ODA0MTQ4NjgsImV4cCI6MTY4MDUwMTI2OH0.OzHz3FMcHDF4Zt3EIR4wN26Z0aNaTX0k-OnSA7_vYHI
Content-Type: application/json

{
    "projectId": 1,
    "updateDate": "2023-02-09",
    "clientAccountManager": "manager1",
    "projectStatus": "status1",
    "projectFitnessIndicator": "g",
    "projectManager": 7
}

###

# UPDATE PROJECT CONCERN // not required

PUT  http://localhost:5000/project-manager/update-project-concern/project/2
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsInVzZXJSb2xlIjoicHJvamVjdE1hbmFnZXIiLCJpYXQiOjE2Nzg3NzgyNDIsImV4cCI6MTY3ODg2NDY0Mn0.Mfg2Da0zK8fF5qmfeXl_Mb3OQuSyHWTeNleRK50ibY4
Content-Type: application/json

{
    "id": 
}


###

# DELETE PROJECT CONCERN

DELETE http://localhost:5000/project-manager/delete-project-concern/2
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsInVzZXJSb2xlIjoicHJvamVjdE1hbmFnZXIiLCJpYXQiOjE2Nzg3NzgyNDIsImV4cCI6MTY3ODg2NDY0Mn0.Mfg2Da0zK8fF5qmfeXl_Mb3OQuSyHWTeNleRK50ibY4

###

# GET ALL PROJECT CONCERNS OF A PROJECT

GET http://localhost:5000/project-manager/project-concerns/project/2
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsInVzZXJSb2xlIjoicHJvamVjdE1hbmFnZXIiLCJpYXQiOjE2Nzg3NzgyNDIsImV4cCI6MTY3ODg2NDY0Mn0.Mfg2Da0zK8fF5qmfeXl_Mb3OQuSyHWTeNleRK50ibY4